import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import Head from "next/head";

// @ts-ignore
import Header from "./components/Header.tsx";
import { AuthProvider } from './context/AuthContext';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <Head>
    
      @import url(&apos;https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap&apos;);
</Head>
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>\
          <Header />
           <div style={{ paddingTop: '120px' }}> 
           {children}
          </div>
        </AuthProvider>      
      </body>
    </html>
    </>
  );
}