import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";

// @ts-ignore
import Header from "./components/Header.tsx";
import { AuthProvider } from './context/AuthContext';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>\
          <Header />
           <div style={{ paddingTop: '120px' }}>  {/* This padding should match or exceed the header's height */}
            {children}
          </div>
        </AuthProvider>      
      </body>
    </html>
  );
}